//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/Scripts/Player/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""movement"",
            ""id"": ""71331439-5492-48cc-b917-f1a10ab75686"",
            ""actions"": [
                {
                    ""name"": ""walkLeft"",
                    ""type"": ""Button"",
                    ""id"": ""85e8138f-d417-463e-bd57-f7cc750ea1ec"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""walkRight"",
                    ""type"": ""Button"",
                    ""id"": ""4ee7d6d0-68a6-4231-94ee-520f581b4566"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b3c1a5d2-cb82-40bc-8709-1a3643c09120"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""walkLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""372563db-7dab-4c37-a77a-a1a4919e2e51"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""walkLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d375bb1f-0e0c-4557-9853-c6f977042787"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""walkRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""96c0751a-65c9-4182-907a-b8164f1cd384"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""walkRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""inventory"",
            ""id"": ""6e2851ba-2339-42ac-adf9-8da17b2c0204"",
            ""actions"": [
                {
                    ""name"": ""pickUpItem"",
                    ""type"": ""Button"",
                    ""id"": ""79604d2d-6cd2-42fe-9517-aa16c23b21bf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""be5fe192-781c-45de-9e16-51ca87f9725c"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""pickUpItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""interactions"",
            ""id"": ""3ff51b34-e378-44c2-8f57-2537a8668427"",
            ""actions"": [
                {
                    ""name"": ""interact"",
                    ""type"": ""Button"",
                    ""id"": ""bc7a8572-d702-4d38-9b75-ba9ed5a5f033"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""39c73170-b700-4780-a23a-63c638dbceff"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // movement
        m_movement = asset.FindActionMap("movement", throwIfNotFound: true);
        m_movement_walkLeft = m_movement.FindAction("walkLeft", throwIfNotFound: true);
        m_movement_walkRight = m_movement.FindAction("walkRight", throwIfNotFound: true);
        // inventory
        m_inventory = asset.FindActionMap("inventory", throwIfNotFound: true);
        m_inventory_pickUpItem = m_inventory.FindAction("pickUpItem", throwIfNotFound: true);
        // interactions
        m_interactions = asset.FindActionMap("interactions", throwIfNotFound: true);
        m_interactions_interact = m_interactions.FindAction("interact", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // movement
    private readonly InputActionMap m_movement;
    private IMovementActions m_MovementActionsCallbackInterface;
    private readonly InputAction m_movement_walkLeft;
    private readonly InputAction m_movement_walkRight;
    public struct MovementActions
    {
        private @PlayerControls m_Wrapper;
        public MovementActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @walkLeft => m_Wrapper.m_movement_walkLeft;
        public InputAction @walkRight => m_Wrapper.m_movement_walkRight;
        public InputActionMap Get() { return m_Wrapper.m_movement; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MovementActions set) { return set.Get(); }
        public void SetCallbacks(IMovementActions instance)
        {
            if (m_Wrapper.m_MovementActionsCallbackInterface != null)
            {
                @walkLeft.started -= m_Wrapper.m_MovementActionsCallbackInterface.OnWalkLeft;
                @walkLeft.performed -= m_Wrapper.m_MovementActionsCallbackInterface.OnWalkLeft;
                @walkLeft.canceled -= m_Wrapper.m_MovementActionsCallbackInterface.OnWalkLeft;
                @walkRight.started -= m_Wrapper.m_MovementActionsCallbackInterface.OnWalkRight;
                @walkRight.performed -= m_Wrapper.m_MovementActionsCallbackInterface.OnWalkRight;
                @walkRight.canceled -= m_Wrapper.m_MovementActionsCallbackInterface.OnWalkRight;
            }
            m_Wrapper.m_MovementActionsCallbackInterface = instance;
            if (instance != null)
            {
                @walkLeft.started += instance.OnWalkLeft;
                @walkLeft.performed += instance.OnWalkLeft;
                @walkLeft.canceled += instance.OnWalkLeft;
                @walkRight.started += instance.OnWalkRight;
                @walkRight.performed += instance.OnWalkRight;
                @walkRight.canceled += instance.OnWalkRight;
            }
        }
    }
    public MovementActions @movement => new MovementActions(this);

    // inventory
    private readonly InputActionMap m_inventory;
    private IInventoryActions m_InventoryActionsCallbackInterface;
    private readonly InputAction m_inventory_pickUpItem;
    public struct InventoryActions
    {
        private @PlayerControls m_Wrapper;
        public InventoryActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @pickUpItem => m_Wrapper.m_inventory_pickUpItem;
        public InputActionMap Get() { return m_Wrapper.m_inventory; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InventoryActions set) { return set.Get(); }
        public void SetCallbacks(IInventoryActions instance)
        {
            if (m_Wrapper.m_InventoryActionsCallbackInterface != null)
            {
                @pickUpItem.started -= m_Wrapper.m_InventoryActionsCallbackInterface.OnPickUpItem;
                @pickUpItem.performed -= m_Wrapper.m_InventoryActionsCallbackInterface.OnPickUpItem;
                @pickUpItem.canceled -= m_Wrapper.m_InventoryActionsCallbackInterface.OnPickUpItem;
            }
            m_Wrapper.m_InventoryActionsCallbackInterface = instance;
            if (instance != null)
            {
                @pickUpItem.started += instance.OnPickUpItem;
                @pickUpItem.performed += instance.OnPickUpItem;
                @pickUpItem.canceled += instance.OnPickUpItem;
            }
        }
    }
    public InventoryActions @inventory => new InventoryActions(this);

    // interactions
    private readonly InputActionMap m_interactions;
    private IInteractionsActions m_InteractionsActionsCallbackInterface;
    private readonly InputAction m_interactions_interact;
    public struct InteractionsActions
    {
        private @PlayerControls m_Wrapper;
        public InteractionsActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @interact => m_Wrapper.m_interactions_interact;
        public InputActionMap Get() { return m_Wrapper.m_interactions; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InteractionsActions set) { return set.Get(); }
        public void SetCallbacks(IInteractionsActions instance)
        {
            if (m_Wrapper.m_InteractionsActionsCallbackInterface != null)
            {
                @interact.started -= m_Wrapper.m_InteractionsActionsCallbackInterface.OnInteract;
                @interact.performed -= m_Wrapper.m_InteractionsActionsCallbackInterface.OnInteract;
                @interact.canceled -= m_Wrapper.m_InteractionsActionsCallbackInterface.OnInteract;
            }
            m_Wrapper.m_InteractionsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @interact.started += instance.OnInteract;
                @interact.performed += instance.OnInteract;
                @interact.canceled += instance.OnInteract;
            }
        }
    }
    public InteractionsActions @interactions => new InteractionsActions(this);
    public interface IMovementActions
    {
        void OnWalkLeft(InputAction.CallbackContext context);
        void OnWalkRight(InputAction.CallbackContext context);
    }
    public interface IInventoryActions
    {
        void OnPickUpItem(InputAction.CallbackContext context);
    }
    public interface IInteractionsActions
    {
        void OnInteract(InputAction.CallbackContext context);
    }
}
